### PR TITLE
Update fortysecondscv.cls to put a new line with <location> within cvitempar (cvitem modified)

### PR DESCRIPTION
**Pull request by DoctorD90**
Added a newcommand 'cvitempar' to place the 3rd argument of basic cvitem (<location>) to a new line when the 2nd argument (<title>) is too long.

### CODE REVIEW

**Comment by PandaScience** [comment]
Cool. Thanks for this contribution!

**Comment by DoctorD90** [comment]
Happy to share and contribute to this cool template :)
I find out another improvable feature: make all corner of a picture rounded.
I will try to implement it in a nice way and I will share it.

**Comment by PandaScience** [comment]
Not sure what you mean. Are you talking about the profile picture?

**Comment by DoctorD90** [comment]
Yes

**Comment by PandaScience** [comment]
Ok, that shouldn't be too hard. Just replace 
`[sharp corners]`
by
`[rounded corners=\profilepicrounding]`
in the 4 relevant places. ;-)

**Comment by DoctorD90** [comment]
Yes! I find it out already :) Thank you - Im trying to add a feature to leave people the choice. Instead to have only "profilepicturecircle", something like "profilepictureroundXOOO" for example where O are the round corners :) so it should be easy for people to let round how they like :)

**Comment by PandaScience** [comment]
Great idea. I created a new issue for that.

**Pull request merged**
