### PR TITLE
Add the circular profile picture feature.

### LINKED ISSUE #3: \profilecircle is documented but not implemented.
Hi there,
Thank you for making this template available!

The option for a circular profile picture is documented (`\profilecircle`), but not implemented.
Unless you have the code laying around already but not committed, I'll give it a go and will let you know if I figure it out.

Cheers,
Ivo

### PR DESCRIPTION
**Pull request by ifokkema**
Add the circular profile picture feature.
- Added option `profilepicstyle` which can be set to `profilecircle` to generate a circular profile picture.
  - The default remains the `\profileroundedcorners` macro.
- Added `profilepicstyle` option to the template file.
  - Also fixed a typo in the `profilepicsize` option.
- Documented the new `profilepicstyle` option.
- Closes #3.

### CODE REVIEW

**Comment by ifokkema** [comment]
@PandaScience 
Hi, do you have some time to look at my PR? If not, just let me know. I have a few other changes that I want to do; if I have an idea of whether you're open to this or not, I can either continue making PRs, or just keep my changes in my personal repo.

**Comment by PandaScience** [comment]
Hi there, sorry for the late reply. Last few weeks were kind of stressful, lots of work, laptop broke, went on vacation...
Not sure if I can manage to work on this project this week but I definitely will merge your PR(s).
Anyways, thank you very much for helping to improve the CV class!

**Comment by ifokkema** [comment]
Thank you for your reply! And sorry to hear about the stress :( Hope you enjoyed your holidays, though!
I'll keep sending things then, no rush whatsoever :)

**Comment by PandaScience** [comment]
Perfect! ;-)
Seems like I indeed forgot or somehow discarded this part of the implementation by accident. Thanks again for the PR.

**Pull request merged**
